name: mininism Github Action
env:
  os: ubuntu-22.04

on:
  push:
    branches: 
      - master
      - minimism
      - develop
  pull_request:
    branches:
      - master
      - minimism
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build minimism
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install libopenmpi-dev libnetcdff-dev \
                               netcdf-bin makedepf90 petsc-dev
      
      - name: compile minimism
        run: |
          cd src
          make -j2

      - uses: actions/cache@v3
        with:
          path: src
          key: ${{ github.sha }}-src

  test:
    name: Test minimism
    runs-on: ubuntu-22.04
    needs:
      - build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: src
          key: ${{ github.sha }}-src

      - name: Install dependencies
        run: |
          sudo apt-get install libopenmpi-dev libnetcdff-dev \
                               netcdf-bin petsc-dev

      - name: Run EISMINT 1
        run: |
          cd tests
          mpirun -n 2 ../src/UFEMISM_program eismint_1.cfg

  unit_tests:
    name: Unit Test
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: src
          key: ${{ github.sha }}-src

      - name: Dependencies
        run: |
          sudo apt-get install libopenmpi-dev libnetcdff-dev \
                               netcdf-bin petsc-dev
          pip install gcovr --upgrade
      - name: build minimism
        run: |
          cd unit_tests
          make UFEMISM_unit_tests
      - name: unit_test
        run: |
          cd unit_tests
          ./UFEMISM_unit_tests
